---
app_configs_001:
  ldap_host_address: directory.yale.edu
  created_at: 2009-07-09 18:39:41
  ldap_base: ou=People,o=yale.edu
  updated_at: 2009-07-09 18:39:41
  id: "2"
  ldap_port: "389"
  auth_types: CAS, authlogic
  ldap_login: uid
  footer: "<marquee><blink>WOOT!!!! WOOT!!!111!!!!one!!!!</blink></marquee>"
  ldap_last_name: sn
  ldap_email: mail
  ldap_first_name: givenname

