--- 
app_configs_001: 
  auth_types: CAS, authlogic
  created_at: 2009-07-09 18:39:41
  footer: <marquee><blink>WOOT!!!! WOOT!!!111!!!!one!!!!</blink></marquee>
  id: "2"
  ldap_base: ou=People,o=yale.edu
  ldap_email: mail
  ldap_first_name: givenname
  ldap_host_address: directory.yale.edu
  ldap_last_name: sn
  ldap_login: uid
  ldap_port: "389"
  updated_at: 2009-07-09 18:39:41
