---
department_configs_001:
  created_at: 2009-06-22 17:27:52
  id: "1"
  department_id: "1"
  schedule_start: "600"
  schedule_end: "1020"
  time_increment: "60"
  grace_period: "7"
  edit_report: f
  updated_at: 2009-06-22 17:27:52
department_configs_002:
  created_at: 2009-06-22 18:09:37
  id: "2"
  department_id: "2"
  schedule_start: "540"
  schedule_end: "1020"
  time_increment: "60"
  grace_period: "0"
  edit_report: f
  updated_at: 2009-06-22 18:09:37

