--- 
department_configs_001: 
  complex: f
  created_at: 2009-06-22 17:27:52
  day: "6"
  day2: "1"
  department_id: "1"
  edit_report: f
  end_of_month: f
  grace_period: "7"
  id: "1"
  monthly: f
  schedule_end: "1020"
  schedule_start: "600"
  time_increment: "15"
  unscheduled_shifts: t
  updated_at: 2009-06-22 17:27:52
  weekend_shifts: t
department_configs_002: 
  complex: f
  created_at: 2009-06-22 18:09:37
  day: "6"
  day2: "1"
  department_id: "2"
  edit_report: f
  end_of_month: f
  grace_period: "0"
  id: "2"
  monthly: f
  schedule_end: "1020"
  schedule_start: "540"
  time_increment: "60"
  unscheduled_shifts: t
  updated_at: 2009-06-22 18:09:37
  weekend_shifts: t
