---
department_configs_001:
<<<<<<< HEAD:preload_data/department_configs.yml
=======
  complex: f
>>>>>>> 0bf4e0c77678b632681e52a72e2adbafe8830b29:preload_data/department_configs.yml
  created_at: 2009-06-22 17:27:52
  day: "6"
  department_id: "1"
  description_min: 10
  end_of_month: f
  grace_period: "7"
  id: "1"
  monthly: f
  printed_message: "This payform has already been printed and may no longer be edited by you. If there is a problem that needs to be addressed, please talk to the administration."
  reason_min: 10
  reminder_message: "Please remember to submit your payform for the week."
  schedule_end: "1020"
  schedule_start: "600"
  show_disabled_cats: f
  time_increment: "15"
  unscheduled_shifts: t
  updated_at: 2009-06-22 17:27:52
  warning_message: "You have not submitted payforms for the weeks ending on the following dates: @weeklist@  Please submit your payforms. If some of the weeks listed are weeks during which you did not work, please just submit a blank payform."
  warning_weeks: 4
  weekend_shifts: t
<<<<<<< HEAD:preload_data/department_configs.yml
department_configs_002:
=======
  printed_message: "This payform has already been printed and may no longer be edited by you.\n If there is a problem that needs to be addressed, please talk to the administration."
  reminder_message: "Please remember to submit your payform for this week."
  warning_message: "Your payform is overdue. Submit it so that we can pay you."
  warning_weeks: "2"
  description_min: "7"
  reason_min: "7"
  punch_clock: t
  show_disabled_cats: f
department_configs_002:
  complex: f
>>>>>>> 0bf4e0c77678b632681e52a72e2adbafe8830b29:preload_data/department_configs.yml
  created_at: 2009-06-22 18:09:37
  day: "6"
  department_id: "2"
  description_min: 10
  end_of_month: f
  grace_period: "0"
  id: "2"
  monthly: f
  printed_message: "This payform has already been printed and may no longer be edited by you. If there is a problem that needs to be addressed, please talk to the administration."
  reason_min: 10
  reminder_message: "Please remember to submit your payform for the week."
  schedule_end: "1020"
  schedule_start: "540"
  show_disabled_cats: f
  time_increment: "60"
  unscheduled_shifts: t
  updated_at: 2009-06-22 18:09:37
  warning_message: "You have not submitted payforms for the weeks ending on the following dates: @weeklist@  Please submit your payforms. If some of the weeks listed are weeks during which you did not work, please just submit a blank payform."
  warning_weeks: 4
  weekend_shifts: t
<<<<<<< HEAD:preload_data/department_configs.yml
=======
  printed_message: "Your payform has been printed."
  reminder_message: "Please remember to submit your payform for this week."
  warning_message: "Your payform is overdue. Submit it so that we can pay you."
  warning_weeks: "2"
  description_min: "7"
  reason_min: "7"
  punch_clock: t
  show_disabled_cats: f
>>>>>>> 0bf4e0c77678b632681e52a72e2adbafe8830b29:preload_data/department_configs.yml

