--- 
userconfigs_001: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "1"
  user_id: "13"
  default_dept: "1"
  view_week:
userconfigs_002: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "2"
  user_id: "14"
  default_dept: "1"
  view_week:
userconfigs_003: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "3"
  user_id: "15"
  default_dept: "1"
  view_week:
userconfigs_004: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "4"
  user_id: "16"
  default_dept: "1"
  view_week:
userconfigs_005: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "5"
  user_id: "17"
  default_dept: "1"
  view_week:
userconfigs_006: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "6"
  user_id: "18"
  default_dept: "1"
  view_week:
userconfigs_007: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "7"
  user_id: "20"
  default_dept: "1"
  view_week:
userconfigs_008: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "8"
  user_id: "21"
  default_dept: "1"
  view_week:
userconfigs_009: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "9"
  user_id: "22"
  default_dept: "1"
  view_week:
userconfigs_010: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "10"
  user_id: "23"
  default_dept: "1"
  view_week:
userconfigs_011: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "11"
  user_id: "24"
  default_dept: "1"
  view_week:
userconfigs_012: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "12"
  user_id: "26"
  default_dept: "1"
  view_week:
userconfigs_013: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "13"
  user_id: "27"
  default_dept: "1"
  view_week:
userconfigs_014: 
  created_at: 2009-06-22 17:42:57
  updated_at: 2009-06-22 17:56:18
  id: "14"
  user_id: "28"
  default_dept: "1"
  view_week:
