# Documentation: http://docs.travis-ci.com/user/build-configuration/
# Documentation: http://docs.travis-ci.com/user/languages/ruby/

# Language
language: ruby

# Version Numbers (possible to define multiple)
# we use ruby 1.9.3p374; available versions are:
# ruby-1.9.3-p547/ruby-1.9.3-p545-railsexpress
# ruby-1.9.3-p545/ruby-1.9.3-p484
rvm:
  - 1.9.3-p484

# Environment Variables
# - DB=sqlite
# - DB=postgresql # This is needed instead of mysql for Heroku
env:
  - DB=mysql

# Run before the script
# - psql -c 'create database shifts' -U postgres
before_script:
  - mysql -e 'create database shifts'

# Jobs to test on the script
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake --trace
