# Site settings
title: "Shifts"
email: "stc-shifts@yale.edu"
username: "YaleSTC"
description: "Shifts is an open-source application that allows the easy tracking of employees who work scheduled hours in various locations and times.  It is developed by Yale STC."
baseurl: "/shifts"
url: "https://yalestc.github.io"

# Build settings
markdown: kramdown
permalink: pretty
